name: Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    setps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'

    - name: Enable Flutter Web
      run: flutter config --enable-web

    - name: Install dependencies
      run: flutter packages get

    - name: Build web
      run: flutter build web

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ 41a84e5503bebada6806bb9435d2ea63747319ea }}
        publish_dir: ./build/web
